# Generated by Django 2.1.10 on 2022-03-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TrashNotes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('note', models.TextField()),
            ],
        ),
    ]
